"""add is_paid to user

Revision ID: 265ef1969d58
Revises: 169d1c0166e7
Create Date: 2026-01-16 12:39:02.201569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265ef1969d58'
down_revision: Union[str, None] = '169d1c0166e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_paid')
    # ### end Alembic commands ###
