"""Add niche to User

Revision ID: 306d9e49275e
Revises: a027cc31c2bb
Create Date: 2026-02-04 22:08:29.551134

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '306d9e49275e'
down_revision: str | None = 'a027cc31c2bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor', sa.Column('last_scanned_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('niche', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'niche')
    op.drop_column('competitor', 'last_scanned_at')
    # ### end Alembic commands ###
