"""Add_destination_to_notification_setting

Revision ID: a027cc31c2bb
Revises: 6447aa8a51f5
Create Date: 2026-01-30 12:11:42.974597

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a027cc31c2bb'
down_revision: str | None = '6447aa8a51f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificationsetting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'webhook', 'in_app', 'slack', 'discord', 'whatsapp', name='notificationchannel'), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificationsetting_id'), 'notificationsetting', ['id'], unique=False)
    op.create_index(op.f('ix_notificationsetting_user_id'), 'notificationsetting', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificationsetting_user_id'), table_name='notificationsetting')
    op.drop_index(op.f('ix_notificationsetting_id'), table_name='notificationsetting')
    op.drop_table('notificationsetting')
    # ### end Alembic commands ###
